entregable_3/veta_bscv/home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("tienda/", views.tienda, name="tienda"),
    path('filtrarProductos/<int:id>',views.filtrarProductos,name="filtrarProductos"),
    path('tienda/producto/<int:idProducto>', views.producto)
]

entregable_3/veta_bscv/login_registro/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("registro/", views.registro, name="registro"),
    #path('loginRegistro/', views.loginRegistro, name="loginRegistro"),
    path('', views.loginVista, name="login"),
    path('logout/', views.logoutVista, name="logout"),
]

entregable_3/veta_bscv/veta_bscv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('login/',include('login_registro.urls'))
]

entregable_3/veta_bscv/login_registro/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, Group, Permission


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El campo correo electronico es obligatorio')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.set_username(email)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)
    
class Usuario(AbstractUser):
    id = models.IntegerField(primary_key=True)
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100,unique=False)
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    celular = models.IntegerField()
    direccion = models.CharField(max_length=1000)
    fechaRegistro = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    groups = models.ManyToManyField(
        Group,
        verbose_name='groups',
        blank=True,
        help_text='The groups this user belongs to.',
        related_name='usuario_groups_set',
        related_query_name='usuario_group',
    )

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name='usuario_permissions_set',
        related_query_name='usuario_permission',
    )

    class Meta:
        permissions = []

entregable_3/veta_bscv/login_registro/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate
from .models import Usuario

class RegistroFormulario(UserCreationForm):
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}))
    password2 = forms.CharField(label="Confirmar Contraseña", widget=forms.PasswordInput(attrs={'type': 'password', 'class': 'form-control', 'placeholder': 'Confirmar Contraseña'}))
    class Meta:
        model = Usuario
        fields = ['nombre', 'apellido', 'celular', 'direccion', 'email', 'password1', 'password2']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'celular': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Celular'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Direccion'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Correo Electronico'}),
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields.pop('username', None)

class LoginFormulario(AuthenticationForm):
    email = forms.CharField(label="Correo Electrónico", required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo Electrónico'}))
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}))

    class Meta:
        model = Usuario
        fields = ['email', 'password']

class EmailAuthenticationForm(AuthenticationForm):
    email = forms.CharField(label="Correo Electrónico", required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo Electrónico'}))
    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}))
    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('username', None)

entregable_3/veta_bscv/login_registro/views.py
import pdb
from django.contrib.auth import  login, logout
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.urls import reverse
from rest_framework_simplejwt.tokens import RefreshToken
from .forms import RegistroFormulario, LoginFormulario, EmailAuthenticationForm
from .models import Usuario
from django.db import transaction

def registro(request):
    context = {}

    if request.method == 'POST':
        form = RegistroFormulario(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']

            if Usuario.objects.filter(email=email).exists():
                mensaje = "Este correo electrónico ya está registrado."
                context['form'] = form
                context['mensaje'] = mensaje
            else:

                usuario = form.save()

                user = authenticate(request, email=email, password=form.cleaned_data['password1'])
                if user is not None:
                    login(request, user)
                    home_url = reverse('home')
                    return redirect(home_url)
                else:
                    print("Field Error:", field.name,  field.errors)

        else:
            mensaje = "Error al crear el ususario, porfavor verifique que todos los campos se ingresen de forma correcta"
            context['form'] = form
            context['mensaje'] = mensaje
            for field in form:
                print("Field Error:", field.name,  field.errors)

    else:
        form = RegistroFormulario()
        context['form'] = form

    return render(request, 'loginRegistro/registro.html', context)

def loginVista(request):
    context = {}

    if request.method == 'POST':
        form = EmailAuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            refresh = RefreshToken.for_user(user)
            user.token = str(refresh.access_token)
            user.save()

            home = reverse('home')
            return redirect(home)
        else:
            print("Formulario no válido. Errores:")
            print(str(form.errors))
            mensaje = "Error al ingresar. verifique los datos de entrada y vuelva a intentarlo."
            context['form'] = form
            context['mensaje'] = mensaje
           
    else:
        form = EmailAuthenticationForm()
        context['form'] = form

    return render(request, 'loginRegistro/login.html', context)

def logoutVista(request):
    logout(request)
    home = reverse('home')
    return redirect(home)

entregable_3/veta_bscv/login_registro/templates/loginRegistro/login.html
{% extends 'loginRegistro/loginRegistro.html' %}

{% block content %}
<div class="card bg-glass">
    <div class="text-center">
        <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(0, 0%, 100%)">
            <span style="color: #e79eff">Login</span>
        </h1>
    </div>
    <div class="card-body px-4 py-2 px-md-5">
        <form form action="" method="post">

            {% csrf_token %}

            {{ form.email.errors }}
            
            <div class="form-outline mb-4">
                <label class="form-label" for="id_email">Correo Electrónico</label>
                {{ form.email }}
            </div>
        
            {{ form.password.errors }}
            <div class="form-outline mb-4">
                <label class="form-label" for="id_password">Contraseña</label>
                {{ form.password }}
            </div>


            <div class="text-center">
                <button type="submit" class="btn btn-success btn-block mb-4">
                    Ingresar
                </button>
            </div>
            <div class="">
                <p>¿No tienes cuenta? <a class="animacion-link" href="{% url 'registro' %}">Puedes registrarte aqui</a>
                </p>
            </div>
        </form>
    </div>
</div>
{% if mensaje %}
    <div id = "mensajeAlertas" class="alert alert-danger" role="alert">
        {{mensaje}}
    </div>
{% endif %}
{% endblock %}

entregable_3/veta_bscv/login_registro/templates/loginRegistro/loginRegistro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href='{% static "css/estilosHome.css" %}'>
    <link rel="stylesheet" href='{% static "css/fontawesome.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/animaciones.css" %}'>
    <script src='{% static "js/animaciones.js" %}'></script>
    <title>VECAV</title>
</head>

<body>

    <!-- Section: Design Block -->
    <section class="background-radial-gradient overflow-hidden">
        <style>
            .background-radial-gradient {
                background-color: hsl(0, 0%, 99%);
                background-image: radial-gradient(650px circle at 0% 0%,
                        hsl(285, 100%, 81%) 15%,
                        hsl(285, 94%, 87%) 35%,
                        hsl(285, 100%, 92%) 75%,
                        hsl(286, 86%, 94%) 80%,
                        transparent 100%),
                    radial-gradient(1250px circle at 100% 100%,
                        hsl(285, 100%, 81%) 15%,
                        hsl(285, 94%, 87%) 35%,
                        hsl(285, 100%, 92%) 75%,
                        hsl(286, 86%, 94%) 80%,
                        transparent 100%);
            }

            #radius-shape-1 {
                height: 220px;
                width: 220px;
                top: -60px;
                left: -130px;
                background: radial-gradient(#eac1f8, #e79eff);
                overflow: hidden;
            }

            #radius-shape-2 {
                border-radius: 38% 62% 63% 37% / 70% 33% 67% 30%;
                bottom: -60px;
                right: -110px;
                width: 300px;
                height: 300px;
                background: radial-gradient(#eac1f8, #e79eff);
                overflow: hidden;
            }

            .bg-glass {
                background-color: hsla(0, 0%, 100%, 0.9) !important;
                backdrop-filter: saturate(200%) blur(25px);
            }
        </style>

        <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
            <div class="row gx-lg-5 align-items-center mb-5">
                <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
                    <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(0, 0%, 100%)">
                        Para que estes<br />
                        <span style="color: #e79eff">Siempre a la moda</span>
                    </h1>

                </div>

                <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
                    <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
                    <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
</body>

</html>

entregable_3/veta_bscv/login_registro/templates/loginRegistro/registro.html
{% extends 'loginRegistro/loginRegistro.html' %}

{% block content %} 
<div class="card bg-glass">
    <div class="text-center">
        <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(0, 0%, 100%)">
            <span style="color: #e79eff">Registro</span>
        </h1>
    </div>
    <div class="card-body px-4 py-2 px-md-5">
        
        <form action="" method="post">

            {% csrf_token %}
            {{ form.password2.errors }}
            {{ form.celular.errors }}
            {{ form.email.errors }}
            <div class="row">
                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="nombrePersona">Nombre</label>
                        {{form.nombre}}
                    </div>
                </div>
                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="apellidoPersona">Apellido</label>
                        {{form.apellido}}
                    </div>
                </div>
                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="apellidoPersona">Celular</label>
                        {{form.celular}}
                    </div>
                </div>

                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="apellidoPersona">Direccion</label>
                        {{form.direccion}}
                    </div>
                </div>
                <div class="col-md-6 mb-4">
                    <div class="form-outline">
                        <label class="form-label" for="correoElectronico">Correo Electronico</label>
                        {{form.email}}
                    </div>
                </div>
                <div class="col-md-6 mb-4">
                    <div class="form-outline mb-4">
                        <label class="form-label" for="password1">Contraseña</label>
                        {{form.password1}}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-outline mb-4">
                        <label class="form-label" for="password2">Confirmar Contraseña</label>
                        {{form.password2}}
                    </div>
                </div>
            </div>
            

            <div class="text-center">
                <button type="submit" id="registrar" class="btn btn-success btn-block mb-4">
                    Registrar
                </button>
            </div>
            <div class="">
                <p>¿Ya tienes una cuenta? <a id="volverLogin" href="{% url 'login' %}"
                        class="animacion-link">Puedes ingresar aqui</a></p>
            </div>
        </form>
    </div>
</div>
{% if mensaje %}
    <div id = "mensajeAlertas" class="alert alert-danger" role="alert">
        {{mensaje}}
    </div>
{% endif %}
{% endblock %}